name: build-release-latest
on:
  push:
    tags-ignore: 'v*'
    branches: '*'

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # build container image for package creation
      - run: /usr/bin/docker build -t ${{ github.job }} -f build/Dockerfile .
      # actually build .mkp file
      - run: /usr/bin/docker run --volume $PWD:/source ${{ github.job }}
      # otherwise .mkp file can't be read by runner
      - run: chmod +r *.mkp
      # upload results
      - uses: actions/upload-artifact@v2
        with:
          path: ./*.mkp
          retention-days: 1