name: build-release-latest
on:
  push:
    tags-ignore: 'v*'
    branches: '*'

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # build container image for package creation
      - run: /usr/bin/docker build -t ${{ github.job }} -f build/Dockerfile .
      - run: /usr/bin/docker run --volume $PWD:/source ${{ github.job }}
      - run: find / -name "*.mkp"